version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - gfortran
    - graphviz
    - libblas-dev
    - liblapack-dev
  tools:
    python: "miniconda3-4.7"

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment.yaml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
