"""Utility functions for tests."""

import base64
import os
from glob import glob

from nipype import logging

from qsirecon import config
from qsirecon.tests.integration_test_data import download_test_data as _download_test_data

LOGGER = logging.getLogger('nipype.utils')


def download_test_data(dset, data_dir=None):
    """Download test data."""
    return _download_test_data(
        dset,
        data_dir=data_dir,
        info=config.loggers.utils.info,
    )


def get_test_data_path():
    """Return the path to test datasets, terminated with separator.

    Test-related data are kept in tests folder in "data".
    Based on function by Yaroslav Halchenko used in Neurosynth Python package.
    """
    return os.path.abspath(os.path.join(os.path.dirname(__file__), 'data') + os.path.sep)


def check_generated_files(output_dir, output_list_file, optional_output_list_file):
    """Compare files generated by qsirecon with a list of expected files."""
    found_files = sorted(glob(os.path.join(output_dir, '**/*'), recursive=True))
    found_files = [os.path.relpath(f, output_dir) for f in found_files]

    # Ignore figures
    found_files = sorted({f for f in found_files if 'figures' not in f})

    # Ignore logs
    found_files = sorted({f for f in found_files if 'log' not in f.split(os.path.sep)})

    with open(output_list_file) as fo:
        expected_files = fo.readlines()
        expected_files = [f.rstrip() for f in expected_files]

    optional_files = []
    if optional_output_list_file:
        with open(optional_output_list_file) as fo:
            optional_files = fo.readlines()
            optional_files = [f.rstrip() for f in optional_files]

    if sorted(found_files) != sorted(expected_files):
        expected_not_found = sorted(set(expected_files) - set(found_files))
        found_not_expected = sorted(set(found_files) - set(expected_files))

        msg = ''
        if expected_not_found:
            msg += '\nExpected but not found:\n\t'
            msg += '\n\t'.join(expected_not_found)

        if found_not_expected:
            # Check that the found files are in the optional file list
            found_not_expected = [f for f in found_not_expected if f not in optional_files]

        if found_not_expected:
            msg += '\nFound but not expected:\n\t'
            msg += '\n\t'.join(found_not_expected)

        if msg:
            raise ValueError(msg)


def reorder_expected_outputs():
    """Load each of the expected output files and sort the lines alphabetically.

    This function is called manually by devs when they modify the test outputs.
    """
    test_data_path = get_test_data_path()
    expected_output_files = sorted(glob(os.path.join(test_data_path, '*_outputs.txt')))
    for expected_output_file in expected_output_files:
        LOGGER.info(f'Sorting {expected_output_file}')

        with open(expected_output_file) as fo:
            file_contents = fo.readlines()

        file_contents = sorted(set(file_contents))

        with open(expected_output_file, 'w') as fo:
            fo.writelines(file_contents)


def freesurfer_license(base_dir):
    """Create a freesurfer license in base_dir."""
    _lic = b'bWFyay5iZXJnbWFuQHVwaHMudXBlbm4uZWR1CjIwMjU5CiAqQ3J2L0QwTXpxcVE2CiBGU3pTdGZYUmlGN2RN'
    license_file = base_dir / 'license.txt'
    with license_file.open('w') as licensef:
        licensef.write(base64.b64decode(_lic).decode('utf-8'))
    return license_file
