channels:
  - conda-forge
dependencies:
  - numpy=1.23.5
  - scipy=1.11
  - fury
  - pip
  - python=3.10
  - setuptools<=54.0.0
  - pip:
    - setuptools<=54.0.0
    - dmri-amico==1.5.4
    - numpy==1.23.5
    - spams==2.6.5.4